-- =====================================================
-- Project : Financial Fraud Detection using SQL
-- Author  : Alisha Khot
-- Database: fraud_detection
-- =====================================================

USE fraud_detection;

-- =====================================================
-- SECTION 1 : DATA EXPLORATION
-- =====================================================

-- View complete dataset
SELECT * FROM transactions;

-- Total number of transactions
SELECT COUNT(*) AS total_transactions
FROM transactions;

-- Total unique users
SELECT COUNT(DISTINCT user_id) AS total_users
FROM transactions;

-- Highest transaction amount
SELECT MAX(amount) AS highest_transaction
FROM transactions;

-- Lowest transaction amount
SELECT MIN(amount) AS lowest_transaction
FROM transactions;

-- Average transaction amount
SELECT ROUND(AVG(amount),2) AS average_transaction
FROM transactions;

-- =====================================================
-- SECTION 2 : BUSINESS ANALYSIS
-- =====================================================

-- Top 10 highest transactions
SELECT *
FROM transactions
ORDER BY amount DESC
LIMIT 10;

-- Total spending by each user
SELECT
    user_id,
    SUM(amount) AS total_spent
FROM transactions
GROUP BY user_id
ORDER BY total_spent DESC;

-- Number of transactions by city
SELECT
    city,
    COUNT(*) AS total_transactions
FROM transactions
GROUP BY city
ORDER BY total_transactions DESC;

-- Total revenue generated by each payment method
SELECT
    payment_method,
    ROUND(SUM(amount),2) AS total_amount
FROM transactions
GROUP BY payment_method
ORDER BY total_amount DESC;

-- Merchant-wise transaction count
SELECT
    merchant,
    COUNT(*) AS transaction_count
FROM transactions
GROUP BY merchant
ORDER BY transaction_count DESC;

-- =====================================================
-- SECTION 3 : FRAUD DETECTION
-- =====================================================

-- High-value transactions (> ₹90,000)
SELECT *
FROM transactions
WHERE amount > 90000
ORDER BY amount DESC;

-- Users with more than 3 transactions
SELECT
    user_id,
    COUNT(*) AS total_transactions
FROM transactions
GROUP BY user_id
HAVING COUNT(*) > 3;

-- Rapid-fire transactions (within 1 minute)
SELECT
    t1.user_id,
    COUNT(*) AS suspicious_transactions
FROM transactions t1
JOIN transactions t2
ON t1.user_id = t2.user_id
AND t1.txn_id <> t2.txn_id
AND ABS(TIMESTAMPDIFF(SECOND,t1.txn_time,t2.txn_time)) <= 60
GROUP BY t1.user_id
HAVING COUNT(*) >= 3;

-- Geographic anomalies
SELECT
    t1.user_id,
    t1.city AS city_1,
    t2.city AS city_2,
    t1.txn_time,
    t2.txn_time
FROM transactions t1
JOIN transactions t2
ON t1.user_id = t2.user_id
AND t1.city <> t2.city
AND ABS(TIMESTAMPDIFF(MINUTE,t1.txn_time,t2.txn_time)) <= 10;

-- =====================================================
-- SECTION 4 : ADVANCED SQL
-- =====================================================

-- Rank highest transactions
SELECT
    txn_id,
    user_id,
    amount,
    RANK() OVER(ORDER BY amount DESC) AS transaction_rank
FROM transactions;

-- Running total for each user
SELECT
    user_id,
    txn_time,
    amount,
    SUM(amount) OVER(
        PARTITION BY user_id
        ORDER BY txn_time
    ) AS running_total
FROM transactions;

-- =====================================================
-- SECTION 5 : BUSINESS INSIGHTS
-- =====================================================

-- Top 5 customers by spending
SELECT
    user_id,
    ROUND(SUM(amount),2) AS total_spent
FROM transactions
GROUP BY user_id
ORDER BY total_spent DESC
LIMIT 5;

-- Top 5 merchants by revenue
SELECT
    merchant,
    ROUND(SUM(amount),2) AS revenue
FROM transactions
GROUP BY merchant
ORDER BY revenue DESC
LIMIT 5;

-- Average transaction amount by city
SELECT
    city,
    ROUND(AVG(amount),2) AS avg_transaction
FROM transactions
GROUP BY city
ORDER BY avg_transaction DESC;
